steps:
  - label: ":lint-roller: Lint Buildkite pipelines (Schema + OPA)"
    key: lint-buildkite-pipelines
    agents:
      queue: OpenTofu
    command: "powershell -NoProfile -ExecutionPolicy Bypass -Command \"Set-Location $$env:BUILDKITE_BUILD_CHECKOUT_PATH; & .\.buildkite\scripts\Test-BuildkitePipelines.ps1\""
