steps:
  - label: ":lint-roller: Lint Buildkite pipelines (Schema + OPA)"
    key: lint-buildkite-pipelines
    agents:
      queue: windows
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "
          $ErrorActionPreference = 'Stop'

          Write-Host '=== Checking prerequisites ==='

          if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
            Write-Error 'Node.js is required on this agent'
          }

          #
          # AJV + YAML
          #
          if (-not (Get-Command ajv -ErrorAction SilentlyContinue)) {
            Write-Host 'AJV not found – installing ajv-cli and yaml...'
            npm install -g ajv-cli yaml | Out-Host
          } else {
            Write-Host 'AJV already installed'
          }

          #
          # OPA
          #
          if (-not (Get-Command opa -ErrorAction SilentlyContinue)) {
            Write-Host 'OPA not found – installing via Chocolatey...'
            choco install opa -y | Out-Host
          } else {
            Write-Host 'OPA already installed'
          }

          Write-Host '=== Downloading Buildkite schema ==='
          Invoke-WebRequest `
            -Uri https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json `
            -OutFile buildkite.schema.json

          Write-Host '=== Linting Buildkite pipelines ==='

          Get-ChildItem -Path .buildkite -Recurse -Include *.yml, *.yaml | ForEach-Object {
            Write-Host ('🔍 Validating ' + $_.FullName)

            $jsonFile = $_.FullName + '.json'
            yaml2json $_.FullName | Out-File -Encoding utf8 $jsonFile

            Write-Host '  → Schema validation'
            ajv validate `
              -s buildkite.schema.json `
              -d $jsonFile `
              --strict=false

            Write-Host '  → OPA policy validation'
            opa eval `
              --fail-defined `
              --format pretty `
              --data opa `
              --input $jsonFile `
              'data.buildkite.deny'
          }
        "
