steps:
  - label: ":lint-roller: Lint Buildkite pipelines (Schema + OPA)"
    key: lint-buildkite-pipelines
    agents:
      queue: OpenTofu
    commands:
      - cd /d "%BUILDKITE_BUILD_CHECKOUT_PATH%"
      - powershell -NoProfile -ExecutionPolicy Bypass -File ".\.buildkite\scripts\Test-BuildkitePipelines.ps1"
