steps:
  - label: ":lint-roller: Lint Buildkite pipelines (Schema + OPA)"
    key: lint-buildkite-pipelines
    agents:
      queue: OpenTofu
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -File "%BUILDKITE_BUILD_CHECKOUT_PATH%/.buildkite/scripts/Test-BuildkitePipelines.ps1"
